Create-animals-table
Patfarmurs/vet_clinic_database pull request #1
Opened 2023-06-06 20:17 UTC by Patfarmurs

## In this PR I : 
>- Create tables in SQL.
>- Insert and query data in SQL

![Screenshot-2](https://github.com/Patfarmurs/vet_clinic_database/assets/70089310/04c37a22-05ec-4b3e-831f-c4d64ea8a1d7)

![Screenshot-1](https://github.com/Patfarmurs/vet_clinic_database/assets/70089310/2f0fd574-7b67-4b2e-a689-d3f17a80503a)
.

2023-06-06 20:30 UTC, Shedrack-Sunday requested changes
Hello @Patfarmurs   👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Kudus on the SQL queries ✔️ 
  
# Required Changes  🌵 

- [ ] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirement


_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-06 20:30 UTC, Shedrack-Sunday commented on README.md
>  This project is [MIT](./LICENSE) licensed.
- [x] Kindly add a License file to the root of your project 👍 
- Including a license file in a README is important as it clarifies the terms and conditions under which the software can be used, providing legal protection and promoting open collaboration while preventing potential misuse or infringement.

2023-06-06 22:50 UTC, Patfarmurs commented on README.md
>  This project is [MIT](./LICENSE) licensed.
Hi @Shedrack-Sunday.
MIT LICENSE is there and the link is working correctly.

2023-06-06 23:00 UTC, codecaiine approved these changes
Hi @Patfarmurs , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Good use of Gitflow ✔️
SQL queries are well setup✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 07:19 UTC, Patfarmurs commented
Thank you @codecaiine.

2023-06-07 07:19 UTC, merged